version: "3.9"

volumes:
  frontend_dist:

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  frontend:
    image: node:20-alpine
    container_name: frontend_builder
    working_dir: /usr/src/app
    volumes:
      - ./app/frontend:/usr/src/app
      - frontend_dist:/usr/share/nginx/html
    env_file:
      - .env
    command: >
      /bin/sh -c "
        npm ci &&
        npm run build &&
        rm -rf /usr/share/nginx/html/* &&
        cp -r dist/* /usr/share/nginx/html/
      "
    restart: "no"

  nginx_proxy:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - '80:80'
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always
