FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y \
    build-essential
RUN pip install --no-cache-dir -r requirements.txt
COPY app/backend .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
